spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/securitypoc
    username: postgres
    password: lovedeep
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format-sql: true
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

